In [1]:
import numpy as np

In [4]:
d = np.matrix([[7, 9, 3, 8], [0, 2, 4, 8], [3, 9, 0, 5],[2, 2, 7, 3]])
v = np.array([1, 2, 3, 4])

In [6]:
print(d)
print(v)

[[7 9 3 8]
 [0 2 4 8]
 [3 9 0 5]
 [2 2 7 3]]
[1 2 3 4]


In [7]:
print(d * d)
print(d + d)
print(d - d)

[[ 74 124 113 167]
 [ 28  56  64  60]
 [ 31  55  80 111]
 [ 41  91  35  76]]
[[14 18  6 16]
 [ 0  4  8 16]
 [ 6 18  0 10]
 [ 4  4 14  6]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
print(v * d)
vv = v[:, np.newaxis]
print(d * vv)

[[24 48 39 51]]
[[66]
 [48]
 [41]
 [39]]
